### ISSUE TITLE
refactor: 기초 환경 수정

### ISSUE THREAD

**Issue by SerenityS** [potenday-23/ticats_app#11]
## Summary
- 기초적인 환경에 대한 수정을 진행합니다.

## Todo
- [x] 필요 패키지 추가
- [x] go_router 적용
- [x] Riverpod 적용
- [x] Folder Structure 변경
- [x] BasePage 추가
- [x] DioProvider 추가
